---
title: "Vsualization 1"
output:
  github_document
---

```{r}
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
```

```{r}
library(tidyverse)
library(ggridges)
```


```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax))

ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point()

weather_df %>%
  drop_na() %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()

plot_weather = 
  weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) 

plot_weather + geom_point()

plot_weather + geom_hex()


ggplot(weather_df, aes(x = tmin, y = tmax, color = name)) + 
  geom_point() +
  geom_smooth()



ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name)) +
  geom_smooth()

ggplot(weather_df, aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha=0.2) +
  geom_smooth(se=FALSE)

ggplot(weather_df, aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha=0.2) +
  geom_smooth(se=FALSE) +
  facet_grid( . ~ name)

ggplot(weather_df, aes(x = date, y = tmax, color = name)) + 
  geom_point(aes(size = prcp), alpha = .5) +
  geom_smooth(se = FALSE) + 
  facet_grid(. ~ name) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

ggplot(weather_df) + geom_point(aes(x = tmax, y = tmin), color = "blue")
ggplot(weather_df) + geom_point(aes(x = tmax, y = tmin, color = "blue"))


ggplot(weather_df, aes(x = tmax, color = name)) + 
  geom_histogram()

ggplot(weather_df, aes(x = tmax, fill = name)) + 
  geom_histogram()

ggplot(weather_df, aes(x = tmax, fill = name)) + 
  geom_histogram(position = "dodge", binwidth = 2)

ggplot(weather_df, aes(x = tmax, fill = name)) + 
  geom_density(alpha = .4, adjust = .5, color = "black")

ggplot(weather_df, aes(x = name, y = tmax, fill = name)) + geom_boxplot()

ggplot(weather_df, aes(x = name, y = tmax)) + 
  geom_violin(aes(fill = name), alpha = .5) + 
  stat_summary(fun = "median", color = "blue")

ggplot(weather_df, aes(x = tmax, y = name)) + 
  geom_density_ridges(scale = .85)

weather_plot = ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) 

ggsave("results/weather_plot.pdf", weather_plot, width = 8, height = 5)
```

```{r fig.width=10}
weather_plot = ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) 
```
